//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace InstantPrintReportsV2Example.Module.BusinessObjects {
  [DefaultClassOptions]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Contact")]
  public partial class Contact : DevExpress.Persistent.BaseImpl.BaseObject {
    private System.String _phoneNumber;
    private System.String _email;
    private System.String _name;
    public Contact(DevExpress.Xpo.Session session)
      : base(session) {
    }
    public System.String Name {
      get {
        return _name;
      }
      set {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    public System.String Email {
      get {
        return _email;
      }
      set {
        SetPropertyValue("Email", ref _email, value);
      }
    }
    public System.String PhoneNumber {
      get {
        return _phoneNumber;
      }
      set {
        SetPropertyValue("PhoneNumber", ref _phoneNumber, value);
      }
    }
  }
}
