'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports DevExpress.ExpressApp.DC
Imports DevExpress.Persistent.Base
Imports DevExpress.Persistent.BaseImpl
Imports DevExpress.Xpo
Namespace InstantPrintReportsV2Example.Module.BusinessObjects
  <DefaultClassOptions, DevExpress.Persistent.Base.ImageNameAttribute("BO_Contact")> _
  Partial Public Class Contact
      Inherits DevExpress.Persistent.BaseImpl.BaseObject

    Private _phoneNumber As System.String
    Private _email As System.String
    Private _name As System.String
    Public Sub New(ByVal session As DevExpress.Xpo.Session)
        MyBase.New(session)
    End Sub
    Public Property Name() As System.String
      Get
        Return _name
      End Get
      Set(ByVal value As System.String)
        SetPropertyValue("Name", _name, value)
      End Set
    End Property
    Public Property Email() As System.String
      Get
        Return _email
      End Get
      Set(ByVal value As System.String)
        SetPropertyValue("Email", _email, value)
      End Set
    End Property
    Public Property PhoneNumber() As System.String
      Get
        Return _phoneNumber
      End Get
      Set(ByVal value As System.String)
        SetPropertyValue("PhoneNumber", _phoneNumber, value)
      End Set
    End Property
  End Class
End Namespace
